### ISSUE TITLE
ncm-query to support different output formats

### ISSUE THREAD

**Issue by msmark** [quattor/ncm-query#6]
Sometimes it is necessary for programs to run `ncm-query` directly to lookup information in the current host profile.  Unfortunately, the output of `ncm-query` is not so easy for a computer to parse.

The contents of a host profile are easy to get hold of from within an NCM component, but problematic when running a tool that is not an NCM component.

I suggest there are multiple ways of tackling this, and we might provide all of them:

   * `ncm-query --format native` that outputs the profile, or portions of the profile, in whatever the native format is (XML or JSON, depending on what is being used).
   * `ncm-query --format json` that outputs the profile, or portions thereof, in JSON.
   * `ncm-query --format xml` for XML format.
   * `ncm-query --format yaml` for YAML format.
   * Perl API that allows a non-NCM component to get hold of a configuration hash similar to that passed through to the `Configure` subroutine in an NCM component (this isn't an `ncm-query` issue, but I thought I'd put it here to keep things all together for discussion at first).

**Comment by jrha** [comment]
`ncm-query --format legacy` for the current output format (including extra newline and superfluous text)

**Comment by jrha** [comment]
I don't think `native` is useful, it makes more sense to me to say what you want.

**Comment by msmark** [comment]
I agree.  I don't actually see a use-case for `native`.

**Comment by stdweird** [comment]
working on it, but won't be finished for 15.4

**Comment by jrha** [comment]
Cool :smile:

**Comment by stdweird** [comment]
@msmark can you give an example of the `xml` output you want?

**Comment by msmark** [comment]
The same XML format as produced by the PAN compiler please.  I have some tools here that take the XML generated by our pan compiler and produces some nice views with it, such as diff with a PAN language style output, and displaying the common set of differences across a large number of host profiles, and reporting on which versions of which packages are used across the estate.

**Comment by stdweird** [comment]
@msmark the issue with xml is the string encoding or a perl module that i can use for that and that is part of EL5. if you have some suggestions, i can give it a try.

other solution is to use CDATA like in http://stackoverflow.com/a/5337851. that will create valid xml, but will make it even more human-unreadable.

**Comment by msmark** [comment]
Well we use XML::LibXML here.

**Comment by stdweird** [comment]
https://github.com/quattor/CCM/pull/65 introduces a new client tool which has format options. i'm not very inclined to backport it to `ncm-query` though. i propose that once that PR gets merged, you try it out and make suggestions for other formats in the CCM repo.

**Comment by jrha** [comment]
Closed by quattor/CCM#65
