### ISSUE TITLE
useprofile command line option does not work as documented

### ISSUE THREAD

**Issue by ned21** [quattor/ncm-query#8]
See https://github.com/quattor/CCM/issues/38 - ncm-query uses Cachemanager::getUnlockedConfiguration() but @stdweird says that an UnlockedConfiguration always gives the latest CID. Therefore if CID is not undef then it must use a LockedConfiguration?

**Comment by stdweird** [comment]
other possible solution is to use `getConfiguration` https://github.com/stdweird/CCM/commit/b7ea01653b24dec3351048e755b7687d4c4ee2c4

**Comment by stdweird** [comment]
new `ccm` tool from https://github.com/quattor/CCM/pull/65 should have everything required. question is do you want this backported to ncm-query. (probably a workshop question)
if you want to switch, https://github.com/quattor/CAF/pull/98 needs to be merged too, as the current `getConfiguration` will trigger the stdout messages (the automagic write permission tests do this)

**Comment by ned21** [comment]
I don't think there's any need to back port, although we should drop the option from ncm-query if it doesn't work.

**Comment by stdweird** [comment]
dropping the option will make legacy scripts fail. we can change the help to `placeholder for legacy oiption that didn't do anything` (and not change anything else)

**Comment by ned21** [comment]
Given that this bug has existed for a long time and no one noticed that it doesn't work, doesn't that suggest no one is actually using it? If options don't work (and therefore shouldn't be used) I think we are OK to explicitly break them?

**Comment by stdweird** [comment]
we certainly don't use the option, so it's fine for me :smile:
@jrha @jouvin any objections on removing the broken option?

**Comment by jrha** [comment]
Nope.
